<?php
//include the header (but make sure it is only once, to not redo any code that shouldn't)
include_once("./includes/header.php");
?>
<p>Go Everywhere is inspired by Scratch, to edit Scratch projects on mobile devices, via HTML5, and community made. Each supported device will have a specific stylesheet, making the interface more user-friendly. And for the devices that work, but are not specifically supported, a general stylesheet will be created, as temporary support for the device until we can get a stylesheet working.</p>
<h1><u>Why should I care? The Scratch Team is already working (or is going to work) on Scratch 2.0 in HTML5.</u></h1>
<p>Correct. However, there are several advantages. Since this is the community's version of Scratch, we can edit however we please. If we see a feature that we want, or don't like, we don't have to wait for official support. We can edit it, and use Go Everywhere until support is added. We can add blocks, user-interface design, and add advanced editing options. Our projects can also be transformed into native apps for Android, Steam, and iOS (however, with each platform, you have to commit the money yourself to submit apps). Certain restrictions will be set at first (no selling GE-made games, and the requirement for having the GE logo in your splash-screen). However, these restrictions may change in the future.</p>
<h1><u>Awesome! How can I help??</u></h1>
<p>Thanks for the offer! We can use the extra help. Before, we all had certain jobs, and were committed to getting them done. Some of us left, and some of us didn't finish our jobs. However, looking around, I noticed that this was not the best option for a community. I was looking, and found MonoGame. MonoGame is a great community project, because anybody can participate. There is no commitment, just do it when you feel like it. So, this is how it is going to work. You must have a <a href="http://github.com/" target="_blank">GitHub</a> account, as we will be using GitHub. You also must fork our main repository (me included, as so I don't mess anything up in the main branch). In your fork, edit and add any features you wish to contribute. Then, submit a pull request. We will merge it into our "Experimental Branch", and see if it will be compatible. If it is, we will merge our "Experimental Branch" into the "Master" branch. If somebody already has submitted a pull request that you wanted to work on, by all means, work on it! If yours is more compatible, or is better, smarter code, we will more likely use it!</p>
<?php
//include the footer
include_once("./includes/footer.php");
?>